Oneledger/protocol

node/action/base.go
node/action/send.go
node/action/types.go
node/app/application.go
node/app/query.go
node/app/register.go
node/app/serial_test.go
node/cmd/fullnode/node.go
node/cmd/olclient/testmint.go
node/cmd/shared/query.go
node/cmd/shared/requests.go
node/data/chainstate.go
node/data/chainstate_test.go
node/data/coin.go
node/data/datastore.go
node/id/account.go
node/version/semantic.go

- Fixed the balance presentation issue
- Messed a bit with the error handling, but needs lots of work
- Pushed to version v0.6.1

Fixed the balance, cleaned up some error handling and bumped the

---

node/version/semantic.go

Bumped the version number.

---

olvm/interpreter/committor/commit.go
olvm/interpreter/committor/types.go
olvm/interpreter/daemon.go
olvm/interpreter/main.go
olvm/interpreter/monitor/monitor.go
olvm/interpreter/monitor/types.go
olvm/interpreter/runner/runner.go
olvm/interpreter/runner/runner_getContract.go
olvm/interpreter/runner/runner_initial.go
olvm/interpreter/runner/types.go
olvm/interpreter/samples/deadloop.js
olvm/interpreter/samples/helloworld.js
olvm/interpreter/samples/jsError.js
olvm/simulator/context.js
olvm/simulator/runner.js
olvm/simulator/simple_contract.js
olvm/test_rpc/configs/common.js
olvm/test_rpc/configs/development.js
olvm/test_rpc/configs/local.js
olvm/test_rpc/configs/production.js
olvm/test_rpc/index.js
olvm/test_rpc/libs/JSONOutput.js
olvm/test_rpc/logger.js
olvm/test_rpc/middlewares/jsonOutput.js
olvm/test_rpc/package-lock.json
olvm/test_rpc/package.json
olvm/test_rpc/providers/appProvider.js
olvm/test_rpc/providers/sessionProvider.js
olvm/test_rpc/server.js
olvm/test_rpc/services/oneledgerNetworkService.js

add OLVM to the code base

---

node/setup/install_bitcoin.sh
node/setup/install_ethereum.sh

Just added a flag to use all cores while building Bitcoin and added auto-yes flags

Just added a flag to use all cores while building Bitcoin

---

Makefile
node/Gopkg.lock
node/Makefile
node/action/register.go
node/app/application.go
node/app/node_name.go
node/app/query.go
node/app/register.go
node/cmd/olclient/account.go
node/cmd/olfullnode/node.go
node/cmd/olfullnode/register.go
node/comm/client.go
node/data/keyvalue.go
node/global/base.go
node/scripts/stopNode
node/serial/functions.go
node/serial/message.go
node/serial/message_test.go
node/serial/primitive_test.go

Fixed an issue with the context not getting set properly. Now some of it is saved, and some of it is dependent on cli args.

Localstate cleanup

---

node/action/base.go
node/action/payment.go
node/app/application.go
node/app/payment.go
node/app/validators.go

Only send one payment transaction - only the "chosen" validator will send the payment transaction.

Distribute payment

---

node/app/application.go
node/app/query.go
node/cmd/olclient/root.go
node/cmd/ollitenode/root.go
node/cmd/shared/query.go
node/cmd/shared/requests.go

changed sequence from being stored in global.Current to database per accountKey

changed sequence from being stored in global.Current to database per accountKey

---

node/action/base.go
node/app/query.go

Made some improvements to use inheritance

Signature improvement

---

node/setup/install_bitcoin.sh

Just a speed improvement for "make setup" in bitcoin stage

Bitcoin setup

---

node/cmd/olconfig/get.go
node/cmd/olfullnode/node.go
node/cmd/olfullnode/root.go
node/config/update.go
node/consensus/config.go
node/global/base.go
node/scripts/data/Emma.toml
node/scripts/startNode
node/scripts/startOneLedger

A basic example of how to get the nodes to contact a seed node and startup. Not sure of the topography of the p2p net, when it starts this way...

Switch from using persistent peers to seed nodes.

---

node/action/apply_validator.go
node/action/base.go
node/action/contract.go
node/action/external_send.go
node/action/payment.go
node/action/register.go
node/action/send.go
node/action/swap.go

Strengthened validation rules for all transaction types

Transaction validations

---

node/data/coin.go

to use decimals instead of exponential format

Fix Coin.Amount float precision and change notation 

---

node/version/semantic.go

Bumped the version numbers to v0.8.0

Upgraded to version v0.8.0

---

node/action/swap.go
node/app/application.go
node/app/query.go
node/app/register.go
node/app/set.go
node/chains/bitcoin/htlc/base.go
node/chains/common/driver.go
node/chains/driver/driver.go
node/chains/driver/driver_bitcoin.go
node/chains/driver/driver_ethereum.go
node/chains/driver/driver_oneledger.go
node/chains/ethereum/client.go
node/cmd/olclient/update.go
node/cmd/shared/requests.go
node/id/account.go
node/tests/register.sh

This is for OLP-172.
I created accounts for Bitcoin and Ethereum.
The implementation can be refined later because we did not hav a correct polymorphism for keys in our account

Chaindriver 172

---

node/scripts/resetBitcoin
node/tests/register.sh

Funded Bitcoin account using their addresses.
Updated keys for accounts.

Fund Bitcoin Account

---

app/application.go
app/rpc_handler.go
client/client.go
cmd/olclient/account.go
cmd/olclient/balance.go
cmd/olclient/list.go
cmd/olclient/send.go
data/balance/balance_store.go
data/keys/address.go
data/req_resp.go
rpc/server.go
serialize/serialize.go

Get balance

---

app/rpc_handler.go
cmd/olclient/loadtest.go

2. fix message counter display bug

1. adding option to randomize receiever address

---

data/balance/balance.go
identity/validators.go

the places where it is invoked was not changed

balance Plus method was changed to return an error

---

.travis.yml

adjust the config.toml pex = true so fullnode can always connect to seed

hot fix for config.toml pex setting

---

action/eth/ext_redeem.go

Added check to reject transaction ,if redeem tracker already exists

tracker check

---

data/ons/genesis.go

new branch

---

.travis.yml
app/context.go

fixed Cfg nil pointer in restful service context

Hotfix service cfg

---

cmd/olfullnode/devnet.go
scripts/resetDev

Erc20 lock

---

event/eth_redeem_transitions.go

commented out log from redeem cleanup transition.

Redeem log1

---

action/eth/check_finalty.go
action/eth/ext_lock.go
app/controller.go
chains/ethereum/online_chain_driver.go
cmd/olfullnode/devnet.go
data/ethereum/store.go
event/eth_lock_transitions.go
scripts/ethereum/main.go
scripts/resetDev
storage/cache.go
storage/session_cache.go
storage/state.go

Fixed Tracker not getting deleted 
Fixed Duplicate Tracker

Hot fix eth transition

---

action/eth/ext_ERC20Lock.go
action/eth/ext_ERC20redeem.go
action/eth/ext_lock.go
action/eth/ext_redeem.go

Added tag "tx.tracker" to transaction result for lock and redeem.

OLP-666: Add tracker tag to ethereum lock and redeem.

---

Makefile
app/context.go
go.mod
identity/validator_set.go
identity/validator_set_test.go
scripts/ons/buy_sell_domain.py
scripts/ons/purchase_expired.py
scripts/ons/renew_domain.py
storage/state.go

create new pointer of store for rpc services

fix the cache problem for service

---

app/context.go
cmd/olfullnode/save_state.go
scripts/ons/create_expiring.py
scripts/ons/purchase_expired.py
storage/chainstate.go
storage/state.go

- enable dump genesis file based on certain block height
- remove expired domain when dumping
- adjust domain expireHeight by minus already past height.

handle domain expiring during save chain state

---

app/application.go
app/context.go
config/server.go

Removed BTC transaction form both "action" router and "internal" router
Removed "btc" Service from default config

OLP-795: Remove all BTC Transactions from the network

---

app/context.go
config/server.go
storage/chainstate.go
storage/chainstate_test.go

1. In config/server.go, define new struct contains recent, every, cycles
2. put this struct into the existing NodeConfig struct
3. give default value for this struct(default values fot recent, every, cycles) in DefaultNodeConfig()
4. in app/context.go, change SetupRotation(10, 100, 10) ’s parameters to what’s in the struct

OLP-798 Export the Chain State Rotation option into server config

---

identity/eth_witness.go
identity/eth_witness_set.go
identity/eth_witness_set_test.go

I added chain type as part of the key of witness in store, so we can differentiate between witnesses working for different chains, like BTC, Ethereum.

Develop feature/olp 797

---

app/application.go
cmd/olclient/account.go
cmd/olclient/main.go
cmd/olclient/send.go

Only register a node account if it is a test environment.

---

Makefile
action/staking/purge_validator_test.go
scripts/testpurgevalidator
service/tx/service.go

added integration test for purgeValidator

Olp 847 validator purge

---

cmd/olfullnode/devnet.go
cmd/olfullnode/genesis.go
scripts/ons/get_all_domains.py
scripts/resetDev

Steps to test 
- Create local secure wallet 
- Generate accounts in this wallet .
- Add addresses from these account to   a) scripts/resetDev nitial_token_holders
b) scripts/ons/get_all_domians (add anyone)
-Add path to domains file in scripts/resetDev, reserved_domains (csv file ). 
-run make reset 
- run  python  scripts/ons/get_all_domians to verify 
Note , to run alltesst run without the initial_token_holders flag .

Changed from reading string to struct

---

app/context.go
client/request_types.go
client/service_client.go
service/map.go
service/query/service.go
status_codes/codes.go
status_codes/error.go

Add RPC call for get witness set

OLP-834 add RPC call for get witness set

---

client/ons_request_types.go
service/query/ons.go

remove `ONSGetDomainsOnSaleReply` and use `ONSGetDomainsReply` instead.

OLP-939 remove the buggy struct and use the correct one

---

scripts/ons/create_sub_domain.py
scripts/ons/sdk/actions.py
service/query/ons.go

created a new query domain service that only returns parent domain. 
and some python integration test changes

OLP-947 Query All Second Level Domain(parent domain) by Owner Address

---

data/ons/types.go
scripts/ons/create_sub_domain.py
scripts/ons/sdk/actions.py
service/query/ons.go

- add new service: ONS_GetSubDomainByName
- add integration test python scripts

OLP-948 Query All Third Level Domains By Second Level Domain

---

scripts/ons/create_sub_domain.py

fix previous commit that omits a check in python scripts

OLP-948-fix

---

Makefile
action/ons/update.go
scripts/ons/sdk/actions.py
scripts/ons/update_domain.py

fix reset uri with empty string and add integration test scripts

OLP-938 for kainos_test branch

---

action/ons/purchase.go

- put domain previous owner in info field of txResult for purchase tx

OLP-943 Add domain previous owner

---

Makefile
client/gov_request_types.go
client/service_client.go
cmd/olclient/gov.go
data/governance/init.go
data/governance/proposal.go
data/governance/proposal_store.go
data/governance/proposal_store_test.go
data/governance/proposal_test.go
data/governance/proposal_vote.go
data/governance/types.go
scripts/governance/cancelProposals.py
scripts/governance/createProposals.py
scripts/governance/expireVotes.py
scripts/governance/fundProposals.py
scripts/governance/governanceCLI.py
scripts/governance/queryProposals.py
scripts/governance/sdk/actions.py
scripts/governance/sdk/common.py
scripts/governance/showProposals.py
scripts/governance/voteProposals.py
scripts/governance/withdrawFunds.py
service/query/governance.go
service/tx/governance.go

https://oneledger.atlassian.net/browse/OLP-909
https://oneledger.atlassian.net/browse/OLP-911
https://oneledger.atlassian.net/browse/OLP-912

Query by proposal ID, type and proposer

---

scripts/ethereum/main.go

Added A function to empty Validator funds

Added Function to empty Validators

---

action/staking/withdraw.go
cmd/olclient/validatorset.go
service/tx/service.go

1. some log and name changed
2. let 'olclient validatorset' output list ordered by active status and by power DESC

Manual Test for Self Staking

---

app/controller.go
cmd/olfullnode/devnet.go
scripts/governance/sdk/actions.py
scripts/governance/withdrawFunds.py

disable rewards, increase funding/voting deadline, add manual option in python script for any deadline

disable rewards

---

app/context.go
app/controller.go
client/rewards_request_types.go
data/rewards/store.go
data/rewards/store_test.go
scripts/reward/getTotalRewards.py
scripts/reward/listRewards.py
scripts/reward/sdk/actions.py
service/query/rewards.go

* Added Query for Total Rewards
* Refactored Maturity Calculation

OLP-1025: Committing query for Reward statistics.

---

action/errors.go
action/staking/unstake.go
action/staking/withdraw.go
status_codes/codes.go

1. check stake address mismatch in Unstake tx
2. check stake address mismatch in Withdraw tx

check stake address mismatches in Unstake/Withdraw transactions

---

app/application.go

Added verification for domain name

Verifying domain name

---

client/service_client.go
cmd/olclient/check_commit.go
cmd/olclient/gov.go
cmd/olclient/main.go
cmd/olclient/send.go
cmd/olclient/sendPool.go
cmd/olclient/stake.go
cmd/olclient/unstake.go
cmd/olclient/withdraw.go
cmd/olclient/withdrawRewards.go
scripts/staking/self_staking.py

change txcommit to txsync and add functionality of checking the tx result periodically until it reaches a timeout

Olclient check result

---

cmd/olclient/gov.go
cmd/olclient/main.go
cmd/olclient/send.go
cmd/olclient/sendPool.go
cmd/olclient/stake.go
cmd/olclient/unstake.go
cmd/olclient/withdraw.go
cmd/olclient/withdrawRewards.go

when checktx fails, do not poll the result

do not poll tx result when tx fails directly at checktx

---

cmd/olfullnode/devnet.go
data/evidence/base.go

updated penalizing options according to Bogdan's changes.

Updated penalizing options

---

cmd/olfullnode/save_state.go

Added evidence options to genesis dump

dump evidence options to genesis

---

app/controller.go

Forced Pool balances lookup to use Deliver state during reward distribution.

Delegation rewards apphash

---

scripts/loadtest/run_tests.py
scripts/loadtest/test_threads.py
scripts/network_delegation/__init__.py
scripts/network_delegation/addNetworkDelegation_load.py
scripts/network_delegation/networkUndelegate_load.py
scripts/network_delegation/sdk/actions.py
scripts/network_delegation/withdrawDelegation_load.py
scripts/sdkcom/constant.py
scripts/sdkcom/tx_load.py

Replaced 'interval' by 'speed' parameter and added loadtest for Undelegation Tx.

Develop feature/olp 1230

---

Makefile
action/network_delegation/add_network_delegation.go
action/network_delegation/init.go
action/network_delegation/network_undelegate.go
action/network_delegation/withdraw_network_delegation.go
action/network_delegation/withdraw_rewards.go
app/controller.go
client/network_delegation_request_types.go
cmd/olfullnode/save_state.go
data/network_delegation/store.go
data/network_delegation/store_test.go
scripts/loadtest/run_tests.py
scripts/network_delegation/__init__.py
scripts/network_delegation/addNetworkDelegation.py
scripts/network_delegation/addNetworkDelegation_load.py
scripts/network_delegation/finalizeRewards.py
scripts/network_delegation/networkUndelegate.py
scripts/network_delegation/networkUndelegate_load.py
scripts/network_delegation/sdk/actions.py
scripts/network_delegation/withdrawDelegation.py
scripts/network_delegation/withdrawDelegation_load.py
scripts/network_delegation/withdrawRewards.py
scripts/network_delegation/withdrawRewards_load.py
scripts/resetDev
scripts/sdkcom/common.py
service/query/network_delegation.go
service/tx/network_delegation.go

1. remove delegation withdraw
2. remove concept of matured amount
3. directly mature the amount to delegator's balance
4. change ToCoinWithBase to ToCoin since sdk will pass the number that already has 18 digit base
5. test

Olp 1267 remove delegation withdraw and matured amount

---

app/controller.go
go.sum

- do the logic in one iteration
- return events for future use
- test

Olp 1267 refactor

---

Makefile
action/network_delegation/finalize_withdraw_rewards.go
action/network_delegation/init.go
app/controller.go
client/network_delegation_request_types.go
cmd/olfullnode/save_state.go
data/network_delegation/init.go
data/network_delegation/rewards_store.go
data/network_delegation/rewards_store_test.go
data/network_delegation/store_test.go
scripts/network_delegation/finalizeRewards.py
scripts/network_delegation/withdrawRewards.py
service/query/network_delegation.go
service/tx/network_delegation.go

- move finalize rewards withdraw logic to `handleDelegationRewards` In controller
- data store change and test
- append events
- integration test and loadtest

Olp 1266 Remove the Finalize Withdraw Rewards

---

action/network_delegation/reinvest_rewards.go

1. Corrected the Tx type for ReinvestRewards transaction.

corrected reinvest Tx Type

---

DOCKER-network/DockerCmd
DOCKER-network/Dockerfile
DOCKER-network/docker-compose-build.yml
DOCKER-network/docker-compose.yml
DOCKER-network/start.sh
DOCKER-network/stop.sh
DOCKER-network/update.sh
cmd/olfullnode/devnet.go
cmd/olfullnode/genesis.go

1. Created default docker-compose files for build and node containers
2. Added scripts for starting, updating and stopping the network (Written in bash, might need to change this for windows)

OLP-1269: Setup docker compose

---

DOCKER-network/dockernet

- modified kill command for stopping containers

OLP-1316: Fix docker for windows

---

Jenkinsfile

Merging new jenkins file to master

Jenkins test
