Oneledger/protocol

- node/app/register.go
- node/id/account.go
- node/id/keys.go
- node/id/serial_test.go
Methods on these types are still wrappers around tendermint types, but not we can extend these types with new methods
> Move away from type aliases for PublicKey and PrivateKey

- node/Makefile
fix unit test
1. stopped verbose logging
2. showing coverage of each package
> Utest coverage

- data/accounts/wallet.go
fix wallet panic on concurrent add accounts
if a set followed by commit is called on the iavl.MutableTree concurrently. The earlier commit saves the un-commited data. If the later
commit has no changes to commit it just panics.
Only way around this is calling the set and commit in an exclusive lock.
> Wallet panic

- .travis.yml
GOPATH environment explictly specified
Revert "GOPATH environment explictly specified"
This reverts commit bcf1ee6e405b3c2bc8f3a961f59d3073fe251780.
execute fulltest before install_c
> travis ci deploy hot fix 

- data/keys/hash_utils.go
- data/keys/keys.go
For ED25519 signatures. The sender has the option to prefix the signature with "SHA512" indicating that the message was hashed with SHA512 before signing; Therefore the protocol will pre-hash the message before verifying the message against the signature. This was done to accommodate the implementation of the Ledger App.
> Added prehash option for signature Verification

- action/btc/add_signature.go
- action/btc/check_finality.go
- action/btc/const.go
- action/btc/ext_lock.go
- action/btc/failed_broadcast_reset.go
- action/btc/helper.go
- chains/bitcoin/chain_driver.go
- chains/bitcoin/validation.go
- client/request_types.go
- cmd/olclient/tracker.go
- data/bitcoin/store.go
- data/bitcoin/tracker.go
- data/keys/btc_multisig.go
- event/btc_broadcast.go
- event/eth_broadcast.go
- scripts/btc/lock/btc_sign.go
- scripts/btc/lock/main.go
- service/btc/prepare_lock.go
- service/btc/prepare_redeem.go
- service/btc/query.go
1. taking multiple inputs for btc lock
2. added validation to make sure wrong inputs or transactions are not sent
3. estimating fees based on txn inputs/ outputs and standard public key/ signature sizes
4. returning money if btc lock fails
> Olp 629 & olp 633

- config/server.go
- rpc/server.go
- scripts/rpcAuth/setup.py
- service/restful.go
Not an issue, works as designed. Grouped the authentication fields in the config together under one section.
> OLP-639: Reorganized Auth configuration fields.

- action/btc/check_finality.go
- data/bitcoin/tracker_test.go
Used Tracker store config to get testnet params. Also updated unit test for tracker store to test config changes.
> OLP-649: Use btc config for testnet params

- Makefile
- action/staking/apply_validator.go
- cmd/olclient/account.go
- cmd/olclient/applyvalidator.go
- cmd/olclient/list.go
- cmd/olclient/main.go
- cmd/olclient/send.go
- data/accounts/wallet.go
- data/accounts/wallet_secure.go
- data/accounts/wallet_secure_test.go
- data/accounts/wallet_test.go
- data/keys/key_store.go
- data/keys/key_store_test.go
- scripts/getValidators
- service/tx/service.go
1. Added Keystore interface
2. Added secure wallet
3. Integrated secure wallet with olclient commands:
account, send, list, applyvalidator.
4. Removed applyvalidator script from alltest. Tested manually instead.
5. Changed requirements from 5 validators to 4 in the get validator script.
CI might fail because of (4) and (5) since it might use the makefile from develop.
> OLP-637: Raw PK is stored in raw format without protection

- Makefile
- action/base.go
- action/init.go
- client/request_types.go
- scripts/txTypes/listTxTypes.py
- service/map.go
- service/query/service.go
1. define a struct to store tx type number and literal name in `action/base.go`
2. register a service in 
1. Context struct and NewMap() func in `service/map.go` with the slice of the struct in previous step
2. Service struct and NewService() func in `service/query/service.go`
3. to avoid hard copying the consts, add an useless Type `EOF` at the end of the const Type listed in `action/init.go` with a manually set number bigger than any Types. And when fetching these consts, I use a loop to fetch anything less than EOF and with a literal not same to “UNKNOWN”.
4. implement this service in `service/query/service.go`
5. add TxTypesRequest and TxTypesReply struct in `client/request_types.go`
6. create `scripts/txTypes/listTxTypes.py` to test this service
7. add `python scripts/listTxTypes.py` …
> OLP-712 rpc call returning all tx types

- app/context.go
- storage/chainstate.go
- storage/chainstate_test.go
1. made some changes to the test file to get correct dynamic result based on test parameters
2. resolved a bug in rotation calculation that `every` could be zero, and cannot be divided when calculate the remainder.
follow up changes:
- wrap elements into struct in storage/chainstate.go:SetupRotation(...)
- change struct type name to make a better fit.(the one in context is called ChainStateRotationCfg, the one in state is called ChainStateRotationSetting)
- capture error and early exit when find negative values in `recent`, `every`, `cycles`
Tested error message when run olfullnode in goland:
```
2020/04/07 23:48:15 listen to: [::]:65390
I[2020-04-07T23:48:15-04:00] storage: Reinitialized From Database version 0 tree_height 0 hash 
Error: failed to create new app: failed to create new app …
```
> OLP-798 polish the test file

- action/staking/apply_validator.go
- cmd/olclient/applyvalidator.go
This is to ensure the staking address is charged for the fee.
> Reversed order of signers during apply validator. 

- action/context.go
- action/eth/ext_ERC20Lock.go
- action/eth/ext_ERC20redeem.go
- action/eth/ext_lock.go
- action/eth/ext_redeem.go
- app/application.go
- app/context.go
- app/controller.go
- cmd/olfullnode/save_state.go
- consensus/genesis.go
- data/ethereum/context.go
- data/ethereum/tracker.go
- event/eth_lock_transitions.go
- event/eth_redeem_transitions.go
- event/eth_transitions_test.go
- identity/eth_witness.go
- identity/eth_witness_set.go
- identity/eth_witness_set_test.go
- identity/eth_witness_test.go
- service/broadcast/service.go
Currently the Validator also witnesses all interoperability Tx.  In the future we would like to remove the witness process from the Validator Nodes, so that it's not burdened with signing the Transactions.  For this story we would like to label the current Validators as witnesses as a first step to create a Witness Node.
> OLP-797: Create ethereum witness store

- app/application.go
- chains/ethereum/online_chain_driver.go
- chains/ethereum/types.go
- event/eth_redeem_transitions.go
- event/eth_sign_redeem.go
- event/eth_verify_redeem.go
- event/internal_service.go
- event/process.go
Tests 
Tested with old binary , Issue with 
- Insufficient funds for validator replicated
- Issue with redeem expiring before validator signature is mine replicated
Tested with fined binary 
- Tracker failer in both cases
- Oeth Refunded in both cases  
- Some validators loose connection to infura and panic .
more than 33% validators loose connection ,and panic
before we bring the nodes back up ,redeem expires ,and  validators cast there No votes ,
After Casting to no vote some of those validators also restart ,becuase of some reason
so there no votes are still in sessioncache and not chainstate ,when they come back up they wont have jobs fo signing ,and the tracker woud be missing that many number of votes
> Redeem hotfix

- action/context.go
- action/ons/purchase.go
- action/ons/update.go
- app/context.go
- cmd/olfullnode/devnet.go
- config/server.go
- service/broadcast/service.go
This fix adds current block height check with config, so that it won't get error when a new node replays the txs.
height to compare is set to 200k
> Domain purchase and reset uri fix

- client/request_types.go
- cmd/olclient/show_node_id.go
- cmd/olfullnode/show_node_id.go
- service/node/service.go
1. We found a way to create a secure wallet account associated with genesis stake address.
2. Added public key information to 'olclient show_node_id' and 'olfullnode show_node_id', so node operator is able to create wallet account by specifying public key and their private key.
> added public key to result of show_node_id command

- data/rewards/calculator.go
- data/rewards/store_cumulative.go
- data/rewards/store_cumulative_test.go
The issue was caused by a different rewards amount from calculation when node is catching up blocks. A block's rewards amount is based on 2 factors, the block generation speed and the amount we have already distributed so far. The difference came from the second factor, the amount of rewards we have already distributed, in catch-up scenario. Now we persisted that amount in DB so we can get the same rewards amount even in catch-up mode.
> Fixed block rewards calculation in catching up scenario

- client/network_delegation_request_types.go
- data/network_delegation/rewards_store.go
- data/network_delegation/rewards_store_test.go
- scripts/network_delegation/finalizeRewards.py
- scripts/network_delegation/sdk/actions.py
- service/query/network_delegation.go
- added one key pair in store to record total amount of rewards that has been generated
- unit test
- query
- Integration test
> Olp 1168 Query: Total rewards acquired by Delegation Pool in its entirety

- client/request_types.go
- client/service_client.go
- service/query/service.go
reason is there is already a health check in restful.go
> Revert health check change

- app/context.go
1. Fixed app hash caused by threading on chain state query/blockEnder
> fixed app hash issue

- action/governance/expireVotes.go
- app/context.go
- app/controller.go
- scripts/governance/expireProposal.py
- scripts/governance/finalizeProposalFail.py
1. Reverted Logic to finalize and expire proposals back to broadcasting internal transactions as the ticket mentioned.
2. Changed the Internal Tx database to use the file system instead of MemDB. This only seems to be used by external apps module.
3. Updated some of the governance test scripts.
> OLP-1356: Internal Transaction Store is using memDB

- app/application.go
- app/controller.go
- data/rewards/calculator.go
- data/rewards/calculator_test.go
- data/rewards/store_cumulative.go
- data/rewards/store_cumulative_test.go
1. Removed Block Store from rewards cumulative db
2. Used Genesis time for initialization
3. Passed current block time as argument in block beginner
4. Refactored Unit tests
> OLP-1358: Remove Blockstore from rewards cumulative DB

- app/application.go
- app/context.go
- cmd/olfullnode/devnet.go
- cmd/olfullnode/save_state.go
- consensus/genesis.go
- data/rewards/store_cumulative_test.go
- identity/eth_witness_set.go
- identity/eth_witness_set_test.go
1. Updated unit tests
2. Refactored function in witness store
3. Dumped the Witnesses separately to the genesis
4. Tested by starting network, 
- deploying smart contract
- stopping
- saving state
- starting back up
- performed lock and redeem
> OLP-1426: Saved Witnesses as separate section in genesis file
